name: Deploy CE

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  deploy-binaries:
    name: Deploy binaries
    runs-on: ubuntu-sbercloud
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries-ubuntu-latest-gcc
          github-token: ${{ secrets.READ_ACTIONS_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Extract binaries
        run: tar xf binaries.tar
      - name: Verify CLI
        run: |
          ./bin/cli --version
          ./bin/cli --help
      - name: Deploy binaries
        run: cp -r bin /opt/compiler-project/
