name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pages.yml'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Initialize repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Sphinx
        run: make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_build/html"

  deploy:
    name: Deploy Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
